import type { TrainingToolAppRuntime } from "./models";

export function installTrainingAppElements(runtime: TrainingToolAppRuntime): void {
function requireElement<T extends Element>(id: string, Type: { new(): T }): T {
    const element = document.getElementById(id);
    if (!(element instanceof Type)) {
      throw new Error(`页面缺少必要元素：${id}`);
    }
    return element;
  }

  runtime.elements = {
    workbookFile: requireElement("workbookFile", HTMLInputElement),
    workbookOverview: requireElement("workbookOverview", HTMLElement),
    workbookHealthPanel: requireElement("workbookHealthPanel", HTMLElement),
    scheduleGapBaseDateInput: requireElement("scheduleGapBaseDateInput", HTMLInputElement),
    scheduleGapHorizonGroup: requireElement("scheduleGapHorizonGroup", HTMLFieldSetElement),
    scheduleGapSummary: requireElement("scheduleGapSummary", HTMLElement),
    scheduleGapTableBody: requireElement("scheduleGapTableBody", HTMLTableSectionElement),
    personValidityForm: requireElement("personValidityForm", HTMLFormElement),
    personValiditySearchInput: requireElement("personValiditySearchInput", HTMLInputElement),
    personValiditySearchButton: requireElement("personValiditySearchButton", HTMLButtonElement),
    personValidityResult: requireElement("personValidityResult", HTMLElement),
    statusLine: requireElement("statusLine", HTMLElement),
    trainingCalendarMonthLabel: requireElement("trainingCalendarMonthLabel", HTMLElement),
    trainingCalendarMonthInput: requireElement("trainingCalendarMonthInput", HTMLInputElement),
    trainingCalendarTodayButton: requireElement("trainingCalendarTodayButton", HTMLButtonElement),
    trainingCalendarReminderList: requireElement("trainingCalendarReminderList", HTMLElement),
    trainingCalendarGrid: requireElement("trainingCalendarGrid", HTMLElement),
    updateValiditySheetSelect: requireElement("updateValiditySheetSelect", HTMLSelectElement),
    updateProjectGroup: requireElement("updateProjectGroup", HTMLElement),
    updateProjectSelectAll: requireElement("updateProjectSelectAll", HTMLInputElement),
    updateProjectSummary: requireElement("updateProjectSummary", HTMLElement),
    updateProjectList: requireElement("updateProjectList", HTMLElement),
    updateMonthSelect: requireElement("updateMonthSelect", HTMLSelectElement),
    workbenchProjectSelect: requireElement("workbenchProjectSelect", HTMLSelectElement),
    workbenchStatusSelect: requireElement("workbenchStatusSelect", HTMLSelectElement),
    workbenchMonthSelect: requireElement("workbenchMonthSelect", HTMLSelectElement),
    workbenchSearchInput: requireElement("workbenchSearchInput", HTMLInputElement),
    workbenchStartDateInput: requireElement("workbenchStartDateInput", HTMLInputElement),
    workbenchEndDateInput: requireElement("workbenchEndDateInput", HTMLInputElement),
    workbenchStatusChart: requireElement("workbenchStatusChart", HTMLElement),
    workbenchProjectChart: requireElement("workbenchProjectChart", HTMLElement),
    qualificationPressureStartMonthInput: requireElement("qualificationPressureStartMonthInput", HTMLInputElement),
    qualificationPressureHorizonSelect: requireElement("qualificationPressureHorizonSelect", HTMLSelectElement),
    qualificationPressureModeGroup: requireElement("qualificationPressureModeGroup", HTMLFieldSetElement),
    qualificationPressureProjectSelect: requireElement("qualificationPressureProjectSelect", HTMLSelectElement),
    qualificationPressureChart: requireElement("qualificationPressureChart", HTMLElement),
    qualificationPressureDetailPanel: requireElement("qualificationPressureDetailPanel", HTMLElement),
    qualificationPressureDetailTitle: requireElement("qualificationPressureDetailTitle", HTMLElement),
    qualificationPressureDetailBody: requireElement("qualificationPressureDetailBody", HTMLTableSectionElement),
    trainingLoadYearInput: requireElement("trainingLoadYearInput", HTMLInputElement),
    trainingLoadProjectSelect: requireElement("trainingLoadProjectSelect", HTMLSelectElement),
    trainingLoadChart: requireElement("trainingLoadChart", HTMLElement),
    crmYearInput: requireElement("crmYearInput", HTMLInputElement),
    crmSummary: requireElement("crmSummary", HTMLElement),
    crmStatsGrid: requireElement("crmStatsGrid", HTMLElement),
    crmParticipationChart: requireElement("crmParticipationChart", HTMLElement),
    crmMonthlyChart: requireElement("crmMonthlyChart", HTMLElement),
    crmRoleChart: requireElement("crmRoleChart", HTMLElement),
    crmDuplicateSummary: requireElement("crmDuplicateSummary", HTMLElement),
    crmDuplicateBody: requireElement("crmDuplicateBody", HTMLTableSectionElement),
    crmMissingBody: requireElement("crmMissingBody", HTMLTableSectionElement),
    exportCrmMissingButton: requireElement("exportCrmMissingButton", HTMLButtonElement),
    exportWorkbenchSelectionButton: requireElement("exportWorkbenchSelectionButton", HTMLButtonElement),
    exportWorkbenchViewButton: requireElement("exportWorkbenchViewButton", HTMLButtonElement),
    simulationProjectSelect: requireElement("simulationProjectSelect", HTMLSelectElement),
    simulationStartDateInput: requireElement("simulationStartDateInput", HTMLInputElement),
    simulationEndDateInput: requireElement("simulationEndDateInput", HTMLInputElement),
    simulationRemarkInput: requireElement("simulationRemarkInput", HTMLInputElement),
    simulationAddSelectionButton: requireElement("simulationAddSelectionButton", HTMLButtonElement),
    simulationClearButton: requireElement("simulationClearButton", HTMLButtonElement),
    simulationSummary: requireElement("simulationSummary", HTMLElement),
    simulationTableBody: requireElement("simulationTableBody", HTMLTableSectionElement),
    updateValidityButton: requireElement("updateValidityButton", HTMLButtonElement),
    workbenchButton: requireElement("workbenchButton", HTMLButtonElement),
    exportButton: requireElement("exportButton", HTMLButtonElement),
    resultSummary: requireElement("resultSummary", HTMLElement),
    statsGrid: requireElement("statsGrid", HTMLElement),
    workbenchProjectSummaryBody: requireElement("workbenchProjectSummaryBody", HTMLTableSectionElement),
    workbenchSelectedPeopleTitle: requireElement("workbenchSelectedPeopleTitle", HTMLElement),
    workbenchSelectedPeopleIntro: requireElement("workbenchSelectedPeopleIntro", HTMLElement),
    workbenchSelectedPeople: requireElement("workbenchSelectedPeople", HTMLElement),
    detailDetails: requireElement("detailDetails", HTMLDetailsElement),
    detailSummaryLabel: requireElement("detailSummaryLabel", HTMLElement),
    detailTableTitle: requireElement("detailTableTitle", HTMLElement),
    detailTableHead: requireElement("detailTableHead", HTMLTableSectionElement),
    detailTableBody: requireElement("detailTableBody", HTMLTableSectionElement),
    skippedDetails: requireElement("skippedDetails", HTMLDetailsElement),
    skippedSummaryLabel: requireElement("skippedSummaryLabel", HTMLElement),
    skippedTableHead: requireElement("skippedTableHead", HTMLTableSectionElement),
    skippedTableBody: requireElement("skippedTableBody", HTMLTableSectionElement),
    projectCards: requireElement("projectCards", HTMLElement)
  };
}
